# Generated by Django 4.1.5 on 2023-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_address_project_cmda_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='land_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
