# Generated by Django 4.1.5 on 2023-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_land_size_alter_project_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frontage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
